config/routes.rb
WhackyRails::Application.routes.draw do
  resources :hackfests

  resources :hacks

  resources :hackers

  match '/proxy' => WhackANode::Proxy.new('/')
  match '/redirect' => WhackANode::Redirect.new('/', "localhost", 8810, true)

end

app/models/hack.rb
#class Hack < ActiveRecord::Base
  #include ActiveModelDnode
  #belongs_to :hacker


   #def self.nodemethod(name)
     #result = DNode.new({ :f => proc { |x,cb| cb.call(x + 8810) }}).listen(5050)
        ##remote.f(5050, proc { |x| ford.call(x) })
      ##end
   #end
#end


class Hack < ActiveRecord::Base
  include ActiveModelDnoded
  belongs_to :hacker
  attr_accessor :nodectl, :nodemethodname
  def self.nodemethod(name)
    define_method(name) do
      @nodemethodname = Proc.new {|name,due| ["get_#{name}_name", "get_#{name}_due"] }
    end
    result = @nodectl.call @nodemethodname

    after_initialize
      @nodectl = nodecall
    end
end

app/models/hacker.rb
class Hacker < ActiveRecord::Base
  has_many :hacks
end

app/models/hackfest.rb
class Hackfest < ActiveRecord::Base
  has_many :hackers
  has_many :hacks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hackers_controller.rb
class HackersController < ApplicationController
  # GET /hackers
  # GET /hackers.xml
  def index
    @hackers = Hacker.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @hackers }
    end
  end

  # GET /hackers/1
  # GET /hackers/1.xml
  def show
    @hacker = Hacker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @hacker }
    end
  end

  # GET /hackers/new
  # GET /hackers/new.xml
  def new
    @hacker = Hacker.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @hacker }
    end
  end

  # GET /hackers/1/edit
  def edit
    @hacker = Hacker.find(params[:id])
  end

  # POST /hackers
  # POST /hackers.xml
  def create
    @hacker = Hacker.new(params[:hacker])

    respond_to do |format|
      if @hacker.save
        format.html { redirect_to(@hacker, :notice => 'Hacker was successfully created.') }
        format.xml  { render :xml => @hacker, :status => :created, :location => @hacker }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @hacker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /hackers/1
  # PUT /hackers/1.xml
  def update
    @hacker = Hacker.find(params[:id])

    respond_to do |format|
      if @hacker.update_attributes(params[:hacker])
        format.html { redirect_to(@hacker, :notice => 'Hacker was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @hacker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hackers/1
  # DELETE /hackers/1.xml
  def destroy
    @hacker = Hacker.find(params[:id])
    @hacker.destroy

    respond_to do |format|
      format.html { redirect_to(hackers_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/hackfests_controller.rb
class HackfestsController < ApplicationController
end

app/controllers/hacks_controller.rb
class HacksController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hackers_helper.rb
module HackersHelper
end

app/helpers/hackfests_helper.rb
module HackfestsHelper
end

app/helpers/hacks_helper.rb
module HacksHelper
end

app/views/hackers/_form.html.erb
<%= form_for(@hacker) do |f| %>
  <% if @hacker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hacker.errors.count, "error") %> prohibited this hacker from being saved:</h2>

      <ul>
      <% @hacker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :irony_value %><br />
    <%= f.text_field :irony_value %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hackers/edit.html.erb
<h1>Editing hacker</h1>

<%= render 'form' %>

<%= link_to 'Show', @hacker %> |
<%= link_to 'Back', hackers_path %>

app/views/hackers/index.html.erb
<h1>Listing hackers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Irony value</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hackers.each do |hacker| %>
  <tr>
    <td><%= hacker.name %></td>
    <td><%= hacker.irony_value %></td>
    <td><%= hacker.email %></td>
    <td><%= link_to 'Show', hacker %></td>
    <td><%= link_to 'Edit', edit_hacker_path(hacker) %></td>
    <td><%= link_to 'Destroy', hacker, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hacker', new_hacker_path %>

app/views/hackers/new.html.erb
<h1>New hacker</h1>

<%= render 'form' %>

<%= link_to 'Back', hackers_path %>

app/views/hackers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @hacker.name %>
</p>

<p>
  <b>Irony value:</b>
  <%= @hacker.irony_value %>
</p>

<p>
  <b>Email:</b>
  <%= @hacker.email %>
</p>


<%= link_to 'Edit', edit_hacker_path(@hacker) %> |
<%= link_to 'Back', hackers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhackyRails</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>